// <auto-generated />
using DvdLibrary.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DvdLibrary.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DvdLibrary.Domain.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "BD2BDC52CF0E74194D3EC97746AA10BE5D2B3EE76DFD53D67AEF00720038D007",
                            Role = 2,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "527F3603FFEAB5056CBE6F7E572699AB11A213FC4BC85C9E4FB6A852A7303A16",
                            Role = 1,
                            Username = "user"
                        });
                });

            modelBuilder.Entity("DvdLibrary.Domain.Entities.DvdMovie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("DvdMovies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Director = "The Wachowskis",
                            DurationMinutes = 136,
                            GenreId = 1,
                            IsAvailable = true,
                            ReleaseYear = 1999,
                            Title = "The Matrix"
                        },
                        new
                        {
                            Id = 2,
                            Director = "Ridley Scott",
                            DurationMinutes = 155,
                            GenreId = 2,
                            IsAvailable = true,
                            ReleaseYear = 2000,
                            Title = "Gladiator"
                        },
                        new
                        {
                            Id = 3,
                            Director = "Christopher Nolan",
                            DurationMinutes = 169,
                            GenreId = 1,
                            IsAvailable = false,
                            ReleaseYear = 2014,
                            Title = "Interstellar"
                        });
                });

            modelBuilder.Entity("DvdLibrary.Domain.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Science fiction med framtidsteknik och rymdäventyr.",
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Högt tempo, konflikter och stora set pieces.",
                            Name = "Action"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Karaktärsdriven berättelse med starka känslor.",
                            Name = "Drama"
                        });
                });

            modelBuilder.Entity("DvdLibrary.Domain.Entities.DvdMovie", b =>
                {
                    b.HasOne("DvdLibrary.Domain.Entities.Genre", "Genre")
                        .WithMany("DvdMovies")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("DvdLibrary.Domain.Entities.Genre", b =>
                {
                    b.Navigation("DvdMovies");
                });
#pragma warning restore 612, 618
        }
    }
}
